package net.veritran.encryption.domain.algorithm

enum class CipherTransformations(val value: String) {

    RSA_ECB_PKCS1PADDING("RSA/ECB/PKCS1Padding"),

    AES_CBC_PKCS5PADDING("AES/CBC/PKCS5PADDING"),
    AES_CBC_NOPADDING("AES/CBC/NOPADDING"),
    AES_ECB_NOPADDING ("AES/ECB/NOPADDING"),
    AES_ECB_PKCS5PADDING ("AES/ECB/PKCS5PADDING"),

    DES_CBC_NOPADDING("DES/CBC/NOPADDING"),
    DES_CBC_PKCS5PADDING("DES/CBC/PKCS5PADDING"),
    DES_ECB_NOPADDING("DES/ECB/NOPADDING"),
    DES_ECB_PKCS5PADDING("DES/ECB/PKCS5PADDING"),

    DESEDE_CBC_NOPADDING("DESEDE/CBC/NOPADDING"),
    DESEDE_CBC_PKCS5PADDING("DESEDE/CBC/PKCS5PADDING"),
    DESEDE_ECB_NOPADDING("DESEDE/ECB/NOPADDING"),
    DESEDE_ECB_PKCS5PADDING("DESEDE/ECB/PKCS5PADDING"),

    RSA_ECB_OAEPWITHSHA_1ANDMGF1PADDING("RSA/ECB/OAEPWITHSHA-1ANDMGF1PADDING"),
    RSA_ECB_OAEPWITHSHA_256ANDMGF1PADDING("RSA/ECB/OAEPWITHSHA-256ANDMGF1PADDING");

    companion object {
        fun validate(value: String): Boolean {
            return values().any { item -> item.value == value }
        }
    }

}
